### ISSUE TITLE
wireframe clavier numérique

### ISSUE THREAD

**Issue by sebastianmel** [sebastianmel/clavier_num-rique#1]
https://wireframe.cc/TUxq9R

**Comment by Herondil** [comment]
Je ne comprends pas comment cela rendrait à droite de la touche entrée, c'est un grand espace vide ?

**Comment by sebastianmel** [comment]
L'espace sera minimiser

**Comment by Herondil** [comment]
Comment ?

**Comment by sebastianmel** [comment]
C'est déjà fait sur le model en ligne

**Comment by Herondil** [comment]
Ok, il n'y a pas de lien sur la page du projet sur github !

**Comment by sebastianmel** [comment]
bien vu ! Merci
