### ISSUE TITLE
Ajuster text-area

### ISSUE THREAD

**Issue by reinepoire** [sebastianmel/clavier_num-rique#2]
Salut ! 

Je remarque que lorsqu'on essaie d'agrandir le text-area, il peut "sortir de l'écran". Peut-être qu'il faudrait lui donner une largeur max. 

Aussi, je vais faire la relou mais il y a une petite faute d'orthographe dans ton titre.

À part ça, je le trouve super ton clavier. J'aime surtout l'idée d'une image de fond qui change en fonction du mode, je n'y avais pas du tout pensé! :)

**Comment by sebastianmel** [comment]
Merci beaucoup, je vais arranger ça !!

**Comment by sebastianmel** [comment]
C'est bon.
